/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.tony.events;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ApplicationInited extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7031823521817385670L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ApplicationInited\",\"namespace\":\"com.linkedin.tony.events\",\"fields\":[{\"name\":\"applicationId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"numTasks\",\"type\":\"int\"},{\"name\":\"host\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public String applicationId;
  @Deprecated public int numTasks;
  @Deprecated public String host;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ApplicationInited() {}

  /**
   * All-args constructor.
   * @param applicationId The new value for applicationId
   * @param numTasks The new value for numTasks
   * @param host The new value for host
   */
  public ApplicationInited(String applicationId, Integer numTasks, String host) {
    this.applicationId = applicationId;
    this.numTasks = numTasks;
    this.host = host;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return applicationId;
    case 1: return numTasks;
    case 2: return host;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: applicationId = (String)value$; break;
    case 1: numTasks = (Integer)value$; break;
    case 2: host = (String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'applicationId' field.
   * @return The value of the 'applicationId' field.
   */
  public String getApplicationId() {
    return applicationId;
  }

  /**
   * Sets the value of the 'applicationId' field.
   * @param value the value to set.
   */
  public void setApplicationId(String value) {
    this.applicationId = value;
  }

  /**
   * Gets the value of the 'numTasks' field.
   * @return The value of the 'numTasks' field.
   */
  public Integer getNumTasks() {
    return numTasks;
  }

  /**
   * Sets the value of the 'numTasks' field.
   * @param value the value to set.
   */
  public void setNumTasks(Integer value) {
    this.numTasks = value;
  }

  /**
   * Gets the value of the 'host' field.
   * @return The value of the 'host' field.
   */
  public String getHost() {
    return host;
  }

  /**
   * Sets the value of the 'host' field.
   * @param value the value to set.
   */
  public void setHost(String value) {
    this.host = value;
  }

  /**
   * Creates a new ApplicationInited RecordBuilder.
   * @return A new ApplicationInited RecordBuilder
   */
  public static com.linkedin.tony.events.ApplicationInited.Builder newBuilder() {
    return new com.linkedin.tony.events.ApplicationInited.Builder();
  }

  /**
   * Creates a new ApplicationInited RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ApplicationInited RecordBuilder
   */
  public static com.linkedin.tony.events.ApplicationInited.Builder newBuilder(com.linkedin.tony.events.ApplicationInited.Builder other) {
    return new com.linkedin.tony.events.ApplicationInited.Builder(other);
  }

  /**
   * Creates a new ApplicationInited RecordBuilder by copying an existing ApplicationInited instance.
   * @param other The existing instance to copy.
   * @return A new ApplicationInited RecordBuilder
   */
  public static com.linkedin.tony.events.ApplicationInited.Builder newBuilder(com.linkedin.tony.events.ApplicationInited other) {
    return new com.linkedin.tony.events.ApplicationInited.Builder(other);
  }

  /**
   * RecordBuilder for ApplicationInited instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ApplicationInited>
    implements org.apache.avro.data.RecordBuilder<ApplicationInited> {

    private String applicationId;
    private int numTasks;
    private String host;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.linkedin.tony.events.ApplicationInited.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.applicationId)) {
        this.applicationId = data().deepCopy(fields()[0].schema(), other.applicationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numTasks)) {
        this.numTasks = data().deepCopy(fields()[1].schema(), other.numTasks);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.host)) {
        this.host = data().deepCopy(fields()[2].schema(), other.host);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ApplicationInited instance
     * @param other The existing instance to copy.
     */
    private Builder(com.linkedin.tony.events.ApplicationInited other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.applicationId)) {
        this.applicationId = data().deepCopy(fields()[0].schema(), other.applicationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.numTasks)) {
        this.numTasks = data().deepCopy(fields()[1].schema(), other.numTasks);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.host)) {
        this.host = data().deepCopy(fields()[2].schema(), other.host);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'applicationId' field.
      * @return The value.
      */
    public String getApplicationId() {
      return applicationId;
    }

    /**
      * Sets the value of the 'applicationId' field.
      * @param value The value of 'applicationId'.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder setApplicationId(String value) {
      validate(fields()[0], value);
      this.applicationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'applicationId' field has been set.
      * @return True if the 'applicationId' field has been set, false otherwise.
      */
    public boolean hasApplicationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'applicationId' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder clearApplicationId() {
      applicationId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'numTasks' field.
      * @return The value.
      */
    public Integer getNumTasks() {
      return numTasks;
    }

    /**
      * Sets the value of the 'numTasks' field.
      * @param value The value of 'numTasks'.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder setNumTasks(int value) {
      validate(fields()[1], value);
      this.numTasks = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'numTasks' field has been set.
      * @return True if the 'numTasks' field has been set, false otherwise.
      */
    public boolean hasNumTasks() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'numTasks' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder clearNumTasks() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'host' field.
      * @return The value.
      */
    public String getHost() {
      return host;
    }

    /**
      * Sets the value of the 'host' field.
      * @param value The value of 'host'.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder setHost(String value) {
      validate(fields()[2], value);
      this.host = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'host' field has been set.
      * @return True if the 'host' field has been set, false otherwise.
      */
    public boolean hasHost() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'host' field.
      * @return This builder.
      */
    public com.linkedin.tony.events.ApplicationInited.Builder clearHost() {
      host = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public ApplicationInited build() {
      try {
        ApplicationInited record = new ApplicationInited();
        record.applicationId = fieldSetFlags()[0] ? this.applicationId : (String) defaultValue(fields()[0]);
        record.numTasks = fieldSetFlags()[1] ? this.numTasks : (Integer) defaultValue(fields()[1]);
        record.host = fieldSetFlags()[2] ? this.host : (String) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
