/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.linkedin.tony.events;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType {
  APPLICATION_INITED, APPLICATION_FINISHED, TASK_STARTED, TASK_FINISHED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"com.linkedin.tony.events\",\"symbols\":[\"APPLICATION_INITED\",\"APPLICATION_FINISHED\",\"TASK_STARTED\",\"TASK_FINISHED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
