/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/apache/submarine/submarine-cloud/pkg/apis/submarine/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSubmarineServers implements SubmarineServerInterface
type FakeSubmarineServers struct {
	Fake *FakeSubmarineV1alpha1
	ns   string
}

var submarineserversResource = schema.GroupVersionResource{Group: "submarine.apache.org", Version: "v1alpha1", Resource: "submarineservers"}

var submarineserversKind = schema.GroupVersionKind{Group: "submarine.apache.org", Version: "v1alpha1", Kind: "SubmarineServer"}

// Get takes name of the submarineServer, and returns the corresponding submarineServer object, and an error if there is any.
func (c *FakeSubmarineServers) Get(name string, options v1.GetOptions) (result *v1alpha1.SubmarineServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(submarineserversResource, c.ns, name), &v1alpha1.SubmarineServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarineServer), err
}

// List takes label and field selectors, and returns the list of SubmarineServers that match those selectors.
func (c *FakeSubmarineServers) List(opts v1.ListOptions) (result *v1alpha1.SubmarineServerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(submarineserversResource, submarineserversKind, c.ns, opts), &v1alpha1.SubmarineServerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SubmarineServerList{ListMeta: obj.(*v1alpha1.SubmarineServerList).ListMeta}
	for _, item := range obj.(*v1alpha1.SubmarineServerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested submarineServers.
func (c *FakeSubmarineServers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(submarineserversResource, c.ns, opts))

}

// Create takes the representation of a submarineServer and creates it.  Returns the server's representation of the submarineServer, and an error, if there is any.
func (c *FakeSubmarineServers) Create(submarineServer *v1alpha1.SubmarineServer) (result *v1alpha1.SubmarineServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(submarineserversResource, c.ns, submarineServer), &v1alpha1.SubmarineServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarineServer), err
}

// Update takes the representation of a submarineServer and updates it. Returns the server's representation of the submarineServer, and an error, if there is any.
func (c *FakeSubmarineServers) Update(submarineServer *v1alpha1.SubmarineServer) (result *v1alpha1.SubmarineServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(submarineserversResource, c.ns, submarineServer), &v1alpha1.SubmarineServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarineServer), err
}

// Delete takes name of the submarineServer and deletes it. Returns an error if one occurs.
func (c *FakeSubmarineServers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(submarineserversResource, c.ns, name), &v1alpha1.SubmarineServer{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSubmarineServers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(submarineserversResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.SubmarineServerList{})
	return err
}

// Patch applies the patch and returns the patched submarineServer.
func (c *FakeSubmarineServers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.SubmarineServer, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(submarineserversResource, c.ns, name, pt, data, subresources...), &v1alpha1.SubmarineServer{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SubmarineServer), err
}
