apiVersion: extensions/v1beta1
#apiVersion: apps/v1
kind: Deployment
metadata:
  name: pytorch-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pytorch-operator
  template:
    metadata:
      labels:
        name: pytorch-operator
    spec:
      containers:
      - command:
        - /pytorch-operator.v1
        - --alsologtostderr
        - -v=1
        - --monitoring-port=8443
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: apache/submarine:pytorch-operator-v1.1.0-gd596e904
        name: pytorch-operator
      serviceAccountName: pytorch-operator
