/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.apache.submarine.server.api.job;

import org.apache.submarine.server.api.spec.JobSpec;

/**
 * The Generic Machine Learning Job in Submarine.
 */
public class Job {
  private JobId jobId;
  private String name;
  private String uid;
  private String status;
  private String acceptedTime;
  private String createdTime;
  private String runningTime;
  private String finishedTime;
  private JobSpec spec;

  /**
   * Get the job id which is unique in submarine
   * @return job id
   */
  public JobId getJobId() {
    return jobId;
  }

  /**
   * Set the job id which generated by submarine
   * @param jobId job id
   */
  public void setJobId(JobId jobId) {
    this.jobId = jobId;
  }

  /**
   * Get the job name which specified by user through the JobSpec
   * @return the job name
   */
  public String getName() {
    return name;
  }

  /**
   * Set the job name which specified by user
   * @param name job name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * The unique identifier for the job, used to retire the job info from the cluster management
   * system.
   *
   * In YARN cluster it best to set the ApplicationId, and in K8s cluster it maybe the job name.
   * @return the unique identifier
   */
  public String getUid() {
    return uid;
  }

  /**
   * Set the job identifier, in YARN cluster it best to set the application id, and in K8s cluster
   * it maybe the uid.
   * @param uid application id (YARN) or uid (K8s)
   */
  public void setUid(String uid) {
    this.uid = uid;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getAcceptedTime() {
    return acceptedTime;
  }

  public void setAcceptedTime(String acceptedTime) {
    this.acceptedTime = acceptedTime;
  }

  public String getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(String creatTime) {
    this.createdTime = creatTime;
  }

  public String getRunningTime() {
    return runningTime;
  }

  public void setRunningTime(String runningTime) {
    this.runningTime = runningTime;
  }

  public String getFinishedTime() {
    return finishedTime;
  }

  public void setFinishedTime(String finishedTime) {
    this.finishedTime = finishedTime;
  }

  public JobSpec getSpec() {
    return spec;
  }

  public void setSpec(JobSpec spec) {
    this.spec = spec;
  }

  public enum Status {
    STATUS_ACCEPTED("Accepted"),
    STATUS_CREATED("Created"),
    STATUS_RUNNING("Running"),
    STATUS_SUCCEEDED("Succeeded"),
    STATUS_DELETED("Deleted");

    private String value;
    Status(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return value;
    }
  }

  public void rebuild(Job job) {
    if (job != null) {
      if (job.getName() != null) {
        this.setName(job.getName());
      }
      if (job.getUid() != null) {
        this.setUid(job.getUid());
      }
      if (job.getSpec() != null) {
        this.setSpec(job.getSpec());
      }
      if (job.getStatus() != null) {
        this.setStatus(job.getStatus());
      }
      if (job.getAcceptedTime() != null) {
        this.setAcceptedTime(job.getAcceptedTime());
      }
      if (job.getCreatedTime() != null) {
        this.setCreatedTime(job.getCreatedTime());
      }
      if (job.getRunningTime() != null) {
        this.setRunningTime(job.getRunningTime());
      }
      if (job.getFinishedTime() != null) {
        this.setFinishedTime(job.getFinishedTime());
      }
    }
  }
}
