# This file allow Apache to hlep us automatically update the website,
# when we push commit to https://github.com/apache/submarine-site
publish:
  whoami: asf-site

github:
  description: "Apache Submarine website"
  homepage: https://submarine.apache.org/
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
