openapi: 3.0.1
info:
  title: Submarine Experiment API
  description: 'The Submarine REST API allows you to create, list, and get experiments. TheAPI is hosted under the /v1/jobs route on the Submarine server. For example,to list experiments on a server hosted at http://localhost:8080, accesshttp://localhost:8080/api/v1/jobs/'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: submarine-dev@submarine.apache.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 0.4.0-SNAPSHOT
servers:
  - url: /api
paths:
  /v1/jobs:
    get:
      tags:
        - jobs
      summary: List jobs
      operationId: listJob
      parameters:
        - name: status
          in: query
          schema:
            type: string
      responses:
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
    post:
      tags:
        - jobs
      summary: Create a job
      operationId: createJob
      requestBody:
        content:
          application/yaml:
            schema:
              $ref: '#/components/schemas/JobSpec'
          application/json:
            schema:
              $ref: '#/components/schemas/JobSpec'
      responses:
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
  '/v1/jobs/{id}':
    get:
      tags:
        - jobs
      summary: Find job by id
      operationId: getJob
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '404':
          description: Job not found
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
    delete:
      tags:
        - jobs
      summary: Delete the job
      operationId: deleteJob
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '404':
          description: Job not found
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
    patch:
      tags:
        - jobs
      summary: Update the job in the submarine server with job spec
      operationId: patchJob
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/yaml:
            schema:
              $ref: '#/components/schemas/JobSpec'
          application/json:
            schema:
              $ref: '#/components/schemas/JobSpec'
      responses:
        '404':
          description: Job not found
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
  /v1/jobs/logs:
    get:
      tags:
        - jobs
      summary: Log jobs
      operationId: listLog
      parameters:
        - name: status
          in: query
          schema:
            type: string
      responses:
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
  '/v1/jobs/logs/{id}':
    get:
      tags:
        - jobs
      summary: Log job by id
      operationId: getLog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '404':
          description: Job not found
        default:
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                $ref: '#/components/schemas/JsonResponse'
  /v1/jobs/ping:
    get:
      tags:
        - jobs
      summary: Ping submarine server
      description: Return the Pong message for test the connectivity
      operationId: ping
      responses:
        '200':
          description: successful operation
          content:
            application/json; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    JsonResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        success:
          type: boolean
        result:
          type: object
        attributes:
          type: object
          additionalProperties:
            type: object
    JobLibrarySpec:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        image:
          type: string
        cmd:
          type: string
        envVars:
          type: object
          additionalProperties:
            type: string
    JobSpec:
      type: object
      properties:
        name:
          type: string
        namespace:
          type: string
        librarySpec:
          $ref: '#/components/schemas/JobLibrarySpec'
        taskSpecs:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/JobTaskSpec'
        projects:
          type: string
    JobTaskSpec:
      type: object
      properties:
        name:
          type: string
        image:
          type: string
        cmd:
          type: string
        envVars:
          type: object
          additionalProperties:
            type: string
        resources:
          type: string
        replicas:
          type: integer
          format: int32
        cpu:
          type: string
        gpu:
          type: string
        memory:
          type: string
